# base image and tag
FROM node:alpine as builder

# no need to use volumes as production envs
# assume no code changes
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .

# production code will be located in
# /app/build
RUN npm run build

# Second phase
FROM nginx
# copy from tagged stage to destination (nginx specific here)
COPY --from=builder /app/build /usr/share/nginx/html