# need a copy of docker running
language: generic
sudo: required
services:
    - docker
# build the image using Dockerfile.dev
before_install:
    - docker build -t andreas/docker-react -f ./frontend/Dockerfile.dev frontend
# Tell travis how to run the test suite
script:
    - docker run -e CI=true andreas/docker-react npm run test
# Tell travis how to deploy the code to AWS
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-939066603867"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY  
    secret_access_key: $AWS_SECRET_KEY
    
